#!/bin/sh

echo "Running Code Sniffer..."
#/usr/local/bin --standard=PSR2 src -n
/usr/local/bin/php-cs-fixer fix . --config=sf23 --dry-run -vv
if [ $? != 0 ]
then
        echo "Fix the error before commit."
        exit 1
fi

exit $?



